### ISSUE TITLE
UI: i18n instead of hardcoded English

### ISSUE THREAD

**Issue by s-l-teichmann** [Intevation/downloadclient#1]
The UI seems to be hard coded in English. This should be done via ResourceBundles or something like this.

**Comment by bernhardreiter** [comment]
confirmed javafx2 still uses ResourceBundles http://stackoverflow.com/questions/10143392/javafx-2-and-internationalization, inspiration and example code can come from https://wald.intevation.org/scm/?group_id=57 di4e river. 
I'll try what I can do.

**Comment by bernhardreiter** [comment]
Will work in an additional branch https://github.com/Intevation/downloadclient/tree/i18n
to not disturb the other ongoing developments.

**Comment by bernhardreiter** [comment]
@s-l-teichmann is the command line client also to be localised?

**Comment by bernhardreiter** [comment]
Question: Do we need to switch locales during one run?

**Comment by s-l-teichmann** [comment]
Not with UI. I would prefer a select based on the default on the platform:
https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#getDefault()
maybe add a system property to enable command line overwriting.

**Comment by s-l-teichmann** [comment]
@bernhardreiter We could localize the command line client, too .. if we have the infrastructure.

**Comment by bernhardreiter** [comment]
8d11e96b09c67d040cfc587d14cbd22e1bab022e shows a simple translation for the main menu.
Trying it, I found out that 
- this version will not fall back to using the key string
- checkstyle will barf if a translation is missing
  So it is the time to think about how to design this. Using a central class (singleton) would have the 
  advantages that:
  - we would a few less lines, because only one import is done and no resource loading is necessary
  - we can customize in one place and make it fall back to the key
  - potentially save typing with a shorter call per message.

**Comment by bernhardreiter** [comment]
777f22c57ac17c6477f539e0cbb8487bfbfb3e25 has an utils.I18n class which is used a few times in View.java.

Possible future improvement: getBundle is called each time, I could not the right place
to use a class variable and initialize it once. However getBundle() should cache according to documentation, so it will not be too bad.

Next Steps: Use I18n in all places where it makes sense.

**Comment by bernhardreiter** [comment]
The gui strings are all prepared for translation and have an EN and a DE variant.
Translating the map module frrom geotools probably should be a separate issue.

**Comment by bernhardreiter** [comment]
New issues created for possible followups:
localization / i18n: diagnostic messages #37
localization / i18n: command line #38
localization/i18n geotools map #39
